import Head from "next/head";
import { ReactElement } from "react";
import Main from "../components/layout/main";
import { NextPageWithLayout } from "./_app";

const About: NextPageWithLayout = () => {
  return (
    <div className={"w-full flex-wrap bg-amber-500"}>
      <Head>
        <title>Backpost - about</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello, Home</div>
    </div>
  );
};

About.getLayout = function getLayout(page: ReactElement) {
  return <Main activeTab={"about"}>{page}</Main>;
};

export default About;
