import Head from "next/head";
import { ReactElement } from "react";
import Main from "../components/layout/main";
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  return (
    <div className={"w-full  flex-wrap bg-amber-500"}>
      <Head>
        <title>Backpost - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello, Home</div>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Main activeTab={"home"}>{page}</Main>;
};

export default Home;
