import Head from "next/head";
import { ReactElement } from "react";
import Main from "../components/layout/main";
import { NextPageWithLayout } from "./_app";

const Messages: NextPageWithLayout = () => {
  return (
    <div className={"h-full w-full bg-amber-500"}>
      <Head>
        <title>Backpost - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello we are on Messages page</div>
    </div>
  );
};

Messages.getLayout = function getLayout(page: ReactElement) {
  return <Main>{page}</Main>;
};

export default Messages;
