import Head from "next/head";
import { ReactElement } from "react";
import Main from "../../components/layout/main";
import { NextPageWithLayout } from "../_app";

const Write: NextPageWithLayout = () => {
  return (
    <div className={"w-full  flex-wrap bg-amber-500"}>
      <Head>
        <title>Write your story</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello, Write</div>
    </div>
  );
};

Write.getLayout = function getLayout(page: ReactElement) {
  return <Main activeTab={"write"}>{page}</Main>;
};

export default Write;
